---
title: "Tugas_Modul4"
author: "Torangto Situngkir"
date: "10/10/2020"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1
```{r}
library(dslabs)
data(murders)
str(murders)
```


1.
```{r}
  pop <- murders$population
  sort(pop)[[1]]
```

2
```{r}
  order(pop)[[1]]
```

3
```{r}
  which.min(pop) == order(pop)[[1]]
```
  
4
```{r}
  
  murders$state[[order(pop)[[1]]]]
```
  
5
```{r}
  
  ranks <- rank(murders$population)
  my_df <- data.frame(name=murders$state,peringkat=ranks)
  my_df
```

6
```{r}
  
  ind = order(my_df$peringkat)
  my_dff = data.frame(name=(sort(murders$state))[ind],Populasi = sort(murders$population),Peringkat = sort(ranks))
  my_dff
```

7
```{r}
  
  population_in_millions <- log10(murders$population)
  total_gun_murders <- murders$total
  plot(population_in_millions,total_gun_murders)
```

8
```{r}
  
  population <- murders$population/100000
  hist(population)
```

9
```{r}
  
  popstate=murders$population/10^5
  boxplot(popstate~region,data=murders)
```